version: "3.3"
services:
  nginx:
    ports:
      - "${NGINX_PORT:-80}:8080"
    build:
      context: .
      dockerfile: ./planing-poker/Dockerfile
    env_file:
      - .env
  ws:
    ports:
      - "${WS_PORT:-9000}:${WS_PORT:-9000}"
    build:
      context: .
      dockerfile: ./web-socket/Dockerfile
    env_file:
      - .env
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#    volumes:
#      - ${MONGO_EXTERNAL_VOLUME}:/data/db