version: "3.3"
services:
  nginx:
    ports:
      - "${NGINX_PORT:-80}:8080"
      - "${NGINX_PORT_SSL:-443}:8081"
    build:
      context: .
      dockerfile: ./planing-poker/Dockerfile
    env_file:
      - .env
  ws:
    ports:
      - "${WS_PORT:-9000}:${WS_PORT:-9000}"
    build:
      context: .
      dockerfile: ./web-socket/Dockerfile
    depends_on:
      - mongo
    env_file:
      - .env
#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - ./certbot/etc:/etc/letsencrypt
#      - ./certbot/var:/var/lib/letsencrypt
#      - ./letsencrypt:/usr/share/letsencrypt
#    command: certonly --staging --webroot --webroot-path=/usr/share/letsencrypt --email 2111072@gmail.com --agree-tos --no-eff-email --force-renewal -d planing-poker.ru
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot --staging renew; sleep 12h & wait $${!}; done;'"
  mongo:
    image: mongo:4.4.12
    ports:
      - "${MONGO_PORT:-27017}:${MONGO_PORT:-27017}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ${MONGO_EXTERNAL_VOLUME}:/data/db